site_name: !!python/object/apply:os.getenv [MK_NAME, "Gistr"]
repo_url: https://github.com/Aetherinox/obsidian-gistr
edit_uri: edit/master/docs/docs/
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - pymdownx.betterem
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.superfences 
  - pymdownx.tabbed
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.blocks.html
  - pymdownx.arithmatex:
      generic: true
theme:
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
    - markdown
  icon:
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
    repo: fontawesome/brands/git-alt 
  name: material
  custom_dir: overrides
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: gistr
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/obsidian.png
  favicon: assets/obsidian.png
  features:
    - content.code.annotate 
    - content.code.select
    - content.code.copy
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.path
    - navigation.top
    - announce.dismiss
extra_css:
  - stylesheets/extra.css
nav:
  - Overview: 'index.md'
  - Members:
    - Member Access: 'members/access.md'
  - Settings:
    - Summary: 'settings/summary.md'
    - Github: 'settings/github.md'
    - Opengist: 'settings/opengist.md'
    - Save & Sync: 'settings/save_and_sync.md'
    - Support: 'settings/support.md'
  - Changelog: 'changelog.md'
  - Tags: 'tags.md'
plugins:
  - search: {}
  - encryptcontent:
      title_prefix: '[🔒]'
      summary: 'Access Restricted'
      placeholder: 'Authentication Code'
      placeholder_user: User
      password_button: True
      password_button_text: 'Authenticate'
     # input_class: 'w3-input' # CSS class used for input username and password
     # button_class: 'w3-button w3-theme-l1 w3-hover-theme' # CSS class for password_button
      decryption_failure_message: 'Authentication code not correct.'
      encryption_info_message: "This information is restricted to certain users with access."
      password_inventory:
        classified:
          - !!python/object/apply:os.getenv [MK_PWD_LEVEL1, "NULL"]
        confidential:
          - !!python/object/apply:os.getenv [MK_PWD_LEVEL2, "NULL"]
  - tags:
      tags_file: tags.md 
  - git-committers:
      repository: Aetherinox/obsidian-gistr
      branch: main
      token: !!python/object/apply:os.getenv [GH_TOKEN, "NULL"]
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
        - custom-skip-class-name
      auto_caption: false
      caption_position: bottom
      background: black
      shadow: false
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: null
      version_selector: true
      css_dir: css
      javascript_dir: js
  - redirects:
      redirect_maps:
        docs/settings/summary.md: settings/summary.md
extra:
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
  generator: false
  version:
    provider: mike
  consent:
    title: Cookie Consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
copyright: >
  Copyright &copy; 2024 - Aetherinox –
  <a href="#__consent">Change cookie settings</a>