name: Build Documentation
on:
  release:
    types:
      - published
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: "Build Documentation"
        run: |
          export MK_NAME=${{ secrets.MK_NAME }}
          export MK_PWD_LEVEL1=${{ secrets.MK_PWD_LEVEL1 }}
          export MK_PWD_LEVEL2=${{ secrets.MK_PWD_LEVEL2 }}

          pip install mkdocs-material mkdocs-redirects mike mkdocs-encryptcontent-plugin mkdocs-git-committers-plugin-2 mkdocs-glightbox pymdown-extensions
          cd docs
          mkdocs gh-deploy --force