# ---------------------------------------------------------------------------------------
#   @parent     : github workflow
#   @desc       : checks for certain phrases in an issue title and body
#   @author     : Aetherinox
#   @url        : https://github.com/Aetherinox
# ---------------------------------------------------------------------------------------

  name: "🎫 Issue: Keyword - Opengist"
  run-name: "🎫 Issue: Keyword - Opengist - ${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
  
  # ---------------------------------------------------------------------------------------
  #   triggers
  # ---------------------------------------------------------------------------------------
  
  on:
    issues:
      types: [opened]
  
  # ---------------------------------------------------------------------------------------
  #   environment variables
  # ---------------------------------------------------------------------------------------
  
  env:
    ACTION_NAME:  OpenGist
    ASSIGN_USER:  Aetherinox
    BOT_NAME_1:   AdminServ
    BOT_NAME_2:   AdminServX
  
  # ---------------------------------------------------------------------------------------
  #   jobs
  # ---------------------------------------------------------------------------------------
  
  jobs:
  
    # ---------------------------------------------------------------------------------------
    #   Check for keyword "OpenGist"
    # ---------------------------------------------------------------------------------------
  
    phrase-search-opengist:
      name:  "Search Phrase › OpenGist"
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
  
        - name: 👄 Keywords › Opengist
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.ADMINSERV_TOKEN_CL }}
            script: |
              const fs            = require( 'fs' );
              const iss_title     = `${ context.payload.issue.title }`;
              const iss_body      = `${ context.payload.issue.body }`;
              let message         = [ "\n<br />\n" ]
  
              let bot_msg =
              `
              ⚠️ It appears you may be looking for OpenGist help.
              - [Opengist Repo](https://github.com/thomiceli/opengist)
              - [Opengist Docs](https://github.com/thomiceli/opengist/blob/master/docs/index.md)
              - [Opengist Demo](https://opengist.thomice.li/all)
  
              If you are looking for OpenGist support, it will be very minimal. Please utilize the links above.
  
              ---
  
              <sub>I am a bot reaching out to you with an automated response. If the above info doesn't apply to you, please ignore it.</sub>
              `;
  
              /*
                  Check for keyword in message title and body
              */

              var findWordList 	        = /(\s*open\s*-?gist\s*)/ig;
              const bFoundMatchTitle    = Boolean( findWordList.test( iss_title ) );
              const bFoundMatchBody     = Boolean( findWordList.test( iss_body ) );
  
              /*
                  found searched word, append / prepare message for bot to send
              */

              if ( bFoundMatchTitle || bFoundMatchBody )
              {
                  message.push  ( bot_msg );
                  bHasMessage   = true;
              }
              
              /*
                  Bot has message to send
              */

              if ( bHasMessage == true )
              {
                  await github.rest.issues.createComment(
                  {
                      issue_number:   context.issue.number,
                      owner:          context.repo.owner,
                      repo:           context.repo.repo,
                      body:           message.join('\n'),
                  } );
              }