# ---------------------------------------------------------------------------------------
#   @parent     : github workflow
#   @desc       : allows you to auto assign labels to new issues and pull requests
#   @author     : Aetherinox
#   @url        : https://github.com/Aetherinox
#
#   requires the following labels to be created in your repo:
#     - bug
#     - feature
#     - urgent
#     - roadmap
# ---------------------------------------------------------------------------------------

  name: "Issues: Assign Label"
  run-name: "New Issue: Assign Label - ${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
  
  on:
    issues:
      types:
        - reopened
        - opened
  
  env:
    LABEL_BUG:      Bug
    LABEL_FEATURE:  Feature
    LABEL_URGENT:   Urgent
    LABEL_ROADMAP:  Roadmap
    ASSIGN_USER:    Aetherinox
    BOT_NAME_1:     AdminServ
    BOT_NAME_2:     AdminServX
    LABELS_JSON: |
      [
        { "name": "Bug", "color": "d73a4a", "description": "Something isn't working" },
        { "name": "Feature", "color": "36552B", "description": "Feature request" },
        { "name": "Urgent", "color": "ccb11d", "description": "This issue required priority." },
        { "name": "Roadmap", "color": "8F1784", "description": "Feature or bug currently planned for implementation." }
      ]
  
  
  jobs:
  
    # ---------------------------------------------------------------------------------------
    #   Verify Existing Labels
    #   This job will ensure you have labels already created in your repo.
    #
    #   All labels come from the JSON table LABELS_JSON.
    # ---------------------------------------------------------------------------------------
  
    Submission_Labels_Verify:
      name: "Labels: Verify"
      runs-on: ubuntu-latest
      permissions: write-all
      steps:
  
        - name: Checkout
          uses: actions/checkout@v3

        # ---------------------------------------------------------------------------------------
        #   Check if repo has labels currently added to issues
        # ---------------------------------------------------------------------------------------
          
        - name: Verify Existing Labels
          uses: actions/github-script@v7
          with:
            script: |
              const labels = JSON.parse( process.env.LABELS_JSON );
              for ( const label of labels )
              {
                  try
                  {
                      await github.rest.issues.createLabel(
                      {
                          owner:        context.repo.owner,
                          repo:         context.repo.repo,
                          name:         label.name,
                          description:  label.description || '',
                          color:        label.color
                      });
                  }
                  catch ( err )
                  {
                      // label already exists
                      if ( err.status === 422 )
                      {
                          console.log( `Label '${label.name}' already exists. Skipping.` );
                      }
                      else
                      {
                          // Log other errors
                          console.error( `Error creating label '${label.name}': ${err}` );
                      }
                  }
              }
  
        # ---------------------------------------------------------------------------------------
        #   Check Title
        #
        #   this job checks to see if a new issue has certain keywords in the title and body
        #   and also if the beginning of the title starts with "bug"
        #
        #   if not, re-name the issue in the format of
        #       Bug: Title Name
        # ---------------------------------------------------------------------------------------

    Submission-Label-Roadmap:
      name:  "Roadmap › Label"
      runs-on: ubuntu-latest
      permissions:
        contents: 'read'
        id-token: 'write'
        issues: 'write'
      steps:

        - name: ${{ env.LABEL_ROADMAP }} › Assignment
          uses: actions/github-script@v7
          with:
            github-token: ${{ secrets.ADMINSERV_TOKEN_CL }}
            script: |
              const iss_body            = `${ context.payload.issue.body }`;
              const iss_title           = `${ context.payload.issue.title }`;
              const iss_title_append    = `${{ env.LABEL_ROADMAP }}:`;
              const add_labels          = [];

              const containsList =
              [
                "roadmap",
                "road map",
                "planned",
              ];

              const bIncludesWord  = containsList.some( s => s.includes( iss_title ) || iss_title.includes( s ) );

              /*
                  Check if title contains word in containsList 
              */

              if ( iss_title.toLowerCase( ).startsWith( iss_title_append.toLowerCase( ) ) || bIncludesWord )
              {

                /*
                    Rename title to contain Roadmap:
                */

                if ( !iss_title.toLowerCase( ).startsWith( iss_title_append.toLowerCase( ) ) )
                {
                    add_labels.push( "${{ env.LABEL_ROADMAP }}" );
                    console.log("yes")

                    const title           = context.payload.issue.title
                    let title_new         = title.replace( /^\broad map\s*?:[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]*]*\s\b/gi, '' );
                    title_new         		= title.replace( /^\broadmap\s*?:[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]*]*\s\b/gi, '' );
                    title_new         		= title.replace( /^\bplanned\s*?:[!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?]*]*\s\b/gi, '' );

                    await github.rest.issues.update(
                    {
                        owner:            context.repo.owner,
                        repo:             context.repo.repo,
                        issue_number:     context.issue.number,
                        title:            `${ iss_title_append } ${ title_new }`,
                        add_labels
                    } );
                }
              }
