# ---------------------------------------------------------------------------------------
#   @parent     : github workflow
#   @desc       : check plugin
#   @author     : Aetherinox
#   @url        : https://github.com/Aetherinox
# ---------------------------------------------------------------------------------------

name: "Plugin Check"
run-name: "Plugin Check"

on:
  pull_request:
    branches:
      - main

# ---------------------------------------------------------------------------------------
#   environment variables
#
#   >   PLUGIN_ID
#           0   = official repo
#           1   = development repo
# ---------------------------------------------------------------------------------------

env:
    PLUGIN_ID: 1

# ---------------------------------------------------------------------------------------
#   jobs
# ---------------------------------------------------------------------------------------

jobs:
  plugin-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: "refs/pull/${{ github.event.number }}/merge"
      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        run: |
          for file in ${ADDED_FILES}; do
            echo "$file was added"
          done

      - name: List all added files
        env:
          ADDED_FILES: ${{ steps.changed-files.outputs.added_files }}
          MODIFIED_FILES: ${{ steps.changed-files.outputs.modified_files }}
      - name: Run Check
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const errors = ${{ env.MODIFIED_FILES }};

            console.log( errors )

