# ---------------------------------------------------------------------------------------
#   @parent     : github workflow
#   @desc       : check plugin
#   @author     : Aetherinox
#   @url        : https://github.com/Aetherinox
# ---------------------------------------------------------------------------------------

name: "Plugin Check"
run-name: "Plugin Check"

on:
  workflow_dispatch:
    inputs:
      PLUGIN_NAME:

      # ---------------------------------------------------------------------------------------
      #   Name of the plugin to use when creating the release zip filename
      #     e.g: gistr-v1.0.0.zip
      # ---------------------------------------------------------------------------------------

        description:  'Name of Plugin'
        required:     true
        default:      'gistr'
        type:         string

      # ---------------------------------------------------------------------------------------
      #   ENABLE:   released version will be marked as pre-release
      #   DISABLE:  release version will be marked as stable / normal release
      # ---------------------------------------------------------------------------------------

      PRERELEASE:
        description:  "Build RC (Pre-release)"
        required:     true
        default:      false
        type:         boolean

      # ---------------------------------------------------------------------------------------
      #   ENABLE:   the changelog generated in releases tab will only display single commits.
      #   DISABLE:  the changelog shows pull requests completed based on their labels
      # ---------------------------------------------------------------------------------------

      CHANGELOG_MODE_COMMIT:
        description:  "Commit Instead of Pull Changelog"
        required:     true
        default:      false
        type:         boolean

      # ---------------------------------------------------------------------------------------
      #   Release Candidate version number
      #   this will be added to the end of your released app in the releases page.
      #     e.g: gistr-v1.0.0-rc.1
      # ---------------------------------------------------------------------------------------

      VERSION_RC:
        description:  "RC (Pre-release) Ver (plugin-rc.v1)"
        required:     false
        type:         string
        default:      1

# ---------------------------------------------------------------------------------------
#   environment variables
# ---------------------------------------------------------------------------------------

env:
    PLUGIN_NAME: gistr

# ---------------------------------------------------------------------------------------
#   jobs
# ---------------------------------------------------------------------------------------

jobs:
  plugin-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Run Check
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');

            let plugin;
            await ( async ( ) =>
            {
                let plugins = [];
                try {
                  plugins = JSON.parse(fs.readFileSync('package.json', 'utf8'));
                } catch (e) {
                  addError('Could not parse `package.json`, invalid JSON. ' + e.message);
                  return;
                }
                console.log( plugins )
            })();
            
    permissions:
      contents: read
      issues: write
      pull-requests: write