# ---------------------------------------------------------------------------------------
#   @parent     : github workflow
#   @desc       : check plugin
#   @author     : Aetherinox
#   @url        : https://github.com/Aetherinox
# ---------------------------------------------------------------------------------------

name: "Plugin Check"
run-name: "Plugin Check"

on:
  workflow_dispatch:
    inputs:
      PLUGIN_NAME:

      # ---------------------------------------------------------------------------------------
      #   Name of the plugin to use when creating the release zip filename
      #     e.g: gistr-v1.0.0.zip
      # ---------------------------------------------------------------------------------------

        description:  'Name of Plugin'
        required:     true
        default:      'gistr'
        type:         string

      # ---------------------------------------------------------------------------------------
      #   ENABLE:   released version will be marked as pre-release
      #   DISABLE:  release version will be marked as stable / normal release
      # ---------------------------------------------------------------------------------------

      PRERELEASE:
        description:  "Build RC (Pre-release)"
        required:     true
        default:      false
        type:         boolean

      # ---------------------------------------------------------------------------------------
      #   ENABLE:   the changelog generated in releases tab will only display single commits.
      #   DISABLE:  the changelog shows pull requests completed based on their labels
      # ---------------------------------------------------------------------------------------

      CHANGELOG_MODE_COMMIT:
        description:  "Commit Instead of Pull Changelog"
        required:     true
        default:      false
        type:         boolean

      # ---------------------------------------------------------------------------------------
      #   Release Candidate version number
      #   this will be added to the end of your released app in the releases page.
      #     e.g: gistr-v1.0.0-rc.1
      # ---------------------------------------------------------------------------------------

      VERSION_RC:
        description:  "RC (Pre-release) Ver (plugin-rc.v1)"
        required:     false
        type:         string
        default:      1

# ---------------------------------------------------------------------------------------
#   environment variables
# ---------------------------------------------------------------------------------------

env:
    PLUGIN_NAME: gistr

# ---------------------------------------------------------------------------------------
#   jobs
# ---------------------------------------------------------------------------------------

jobs:
  plugin-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Run Check
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');

            const escapeHtml = (unsafe) => unsafe.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#039;');
            let plugin;
            await ( async ( ) =>
            {
                // Validate plugin repo

                let plugins = require('./package.json');

                /*
                    splits up the JSON key:
                        "repo": "Aetherinox/obsidian-gistr"

                    result:
                        [ 'Aetherinox', 'obsidian-gistr' ]
                /*

                let repoInfo = plugins.repository.url;
                console.log( `${repoInfo}` );
                if ( repoInfo.length !== 2 )
                {
                    addError( `It seems like you made a typo in the repository field \`${plugin.repo}\`.` );
                }

                let [ owner, repo ] = repoInfo;
                console.log( `Repo info: ${owner}/${repo}` );

                try
                {
                    const repository = await github.rest.repos.get({owner, repo});
                    if (!repository.data.has_issues)
                    {
                        addWarning('Your repository does not have issues enabled. Users will not be able to report bugs and request features.');
                    }
                }
                catch ( e )
                {
                    addError(`It seems like you made a typo in the repository field \`${plugin.repo}\`.`);
                }

                console.log( "Got repo info" )


                if (manifest)
                {
                    console.log( "Found manifest.json" )
                }

                try
                {
                    await github.rest.licenses.getForRepo( { owner, repo } );
                }
                catch ( e )
                {
                    addWarning(`Your repository does not include a license. It is generally recommended for open-source projects to have a license. Go to <https://choosealicense.com/> to compare different open source licenses.`);
                }
            })();
            
            if (errors.length > 0 || warnings.length > 0) {
              let message = [`#### Hello!\n`]
              message.push(`**I found the following issues in your plugin submission**\n`);

              if (errors.length > 0) {
                message.push(`**Errors:**\n`);
                message = message.concat(errors);
                message.push(`\n---\n`);
              }
              if (warnings.length > 0) {
                message.push(`**Warnings:**\n`);
                message = message.concat(warnings);
                message.push(`\n---\n`);
              }

              message.push(`<sup>This check was done automatically. Do <b>NOT</b> open a new PR for re-validation. Instead, to trigger this check again, make a change to your PR and wait a few minutes, or close and re-open it.</sup>`);

              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message.join('\n'),
              });
            }
            const labels = [];

            if (errors.length > 0) {
              labels.push("Validation failed");
              core.setFailed("Failed to validate plugin");
            }

            if (errors.length === 0) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.issue.number,
                title: `Add plugin: ${plugin.name}`
              });

              if(!context.payload.pull_request.labels.filter(label => label.name === 'Changes requested').length > 0) {
                labels.push("Ready for review");
              }
            }
            if (context.payload.pull_request.labels.filter(label => label.name === 'Changes requested').length > 0) {
              labels.push('Changes requested');
            }
            if (context.payload.pull_request.labels.filter(label => label.name === 'Additional review required').length > 0) {
              labels.push('Additional review required');
            }
            if (context.payload.pull_request.labels.filter(label => label.name === 'Minor changes requested').length > 0) {
              labels.push('Minor changes requested');
            }
            if (context.payload.pull_request.labels.filter(label => label.name === 'requires author rebase').length > 0) {
              labels.push('requires author rebase');
            }
            if (context.payload.pull_request.labels.filter(label => label.name === 'Installation not recommended').length > 0) {
              labels.push('Installation not recommended');
            }
            if (context.payload.pull_request.labels.filter(label => label.name === 'Changes made').length > 0) {
              labels.push('Changes made');
            }
            if (context.payload.pull_request.labels.filter(label => label.name === 'Skipped code scan').length > 0) {
              labels.push('Skipped code scan');
            }
            labels.push('plugin');

            await github.rest.issues.setLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels,
            });
    permissions:
      contents: read
      issues: write
      pull-requests: write